# CAUTION: CHANGING ANYTHING HERE THAT YOU SHOULDN'T, WILL DISRUPT COMPLETELY THE SENSOR CONNECTION AND/OR FUNCTIONALLITY
# YOU MAY ONLY GET A NEW UNIQUE "api_encryption_key_ap_password_ota_password" FOR YOUR SECRETS FILE
# FROM HERE: https://esphome.io/components/api/#configuration-variables
# AND - FOR ADVANCED USERS ONLY - CHANGE THE LOGS LEVEL AS MENTIONED BELOW
esphome:
  name: esp32-multisensor
  friendly_name: ESP32 Multisensor
  name_add_mac_suffix: true
esp32:
  board: esp32dev
  framework:
    type: esp-idf
api:
ota:
# Optional: Change your Logs level to your liking (se here: https://esphome.io/components/logger/#log-levels)
logger:
  level: DEBUG
  logs:
    sensor: WARN
    text_sensor: WARN
wifi:
  id: wifi_component
  ap:
    password: !secret wifi_password
improv_serial:
captive_portal:
esp32_improv:
  id: improv_component
  authorizer: none
packages:
  remote_package_shorthand: github://djgenesis/esp32-multisensor/remote_package.yaml
