esphome:
  name: esp32-multisensor
  friendly_name: ESP32 Multisensor
  name_add_mac_suffix: true
esp32:
  board: esp32dev
  framework:
    type: esp-idf
api:
  encryption:
    key: !secret api_encryption_key_ap_password_ota_password
ota:
  - platform: esphome
    password: !secret api_encryption_key_ap_password_ota_password
logger:
  level: DEBUG
  logs:
    sensor: WARN
    text_sensor: WARN
wifi:
  id: wifi_component
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    password: !secret api_encryption_key_ap_password_ota_password
improv_serial:
captive_portal:
esp32_improv:
  id: improv_component
  authorizer: none
packages:
  remote_package_shorthand: github://djgenesis/esp32-multisensor/remote_package.yaml
